<?php
namespace App\Exports;

use App\Models\Session;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class GetAllProduct implements FromCollection, WithHeadings
{
    /**
     * @return \Illuminate\Support\Collection
     */
    protected $shopurl;

    public function __construct($shopurl)
    {
        $this->shopurl = $shopurl;
    }

    public function collection()
    {

        $query = 'query {
            products(first: 50) {
              edges {
                cursor
                node {
                  id
                  title
                  descriptionHtml
                  vendor
                  productType
                  handle
                  tags
                  variants(first: 1) {
                    edges {
                      cursor
                      node {
                        id
                        title
                        sku
                      }
                    }
                  }
                }
              }
            }
          }
          ';

        $body = [
            "query" => $query,
        ];

        $token = Session::where('shop',$this->shopurl)->first('access_token');
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://' . $this->shopurl . '/admin/api/2022-07/graphql.json');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($body));

        $headers = array();
        $headers[] = 'Content-Type: application/json';
        $headers[] = 'X-Shopify-Access-Token: '.$token->access_token.'';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        $response = json_decode($result, true);
        $products = $response['data']['products']['edges'];

        $data = $products;
        foreach ($products as $data) {

            $product = $data['node'];

            $variant = $product['variants']['edges'];

            foreach ($variant as $data) {

                $variantdata = ($data['node']);

                // print_r($product);
                // exit;

                $arrofcsv[] = array(
                    'Product Id' => $product['id'],
                    'Product Title' => $product['title'],
                    'Body (HTML)' => $product['descriptionHtml'],
                    'Vendor' => $product['vendor'],
                    'Product Type' => $product['productType'],
                    'Handle' => $product['handle'],
                    'Product Tags' => $product['tags'],
                    'Variant Title' => $variantdata['title'],
                    'Price' => '',
                    'SKU' => $variantdata['sku'],
                    'Option 1' => $variantdata['title'],
                    'Option 2' => '',
                    'Option 3' => '',

                );
            }

        }

        // print_r($product);
        // exit;
        $productsdata = collect($arrofcsv);

        return $productsdata;
    }
    public function headings(): array
    {
        return [
            'Product Id',
            'Product Title',
            'Body (HTML)',
            'Vendor',
            'Product Type',
            'Handle',
            'Product Tags',
            'Variant Title',
            'Price',
            'SKU',
            'Option 1',
            'Option 2',
            'Option 3',

        ];
    }
}
