<?php

namespace App\Http\Controllers;

use App\Models\Charge;
use App\Models\Session;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class PlanController extends Controller
{
    public function PlanCreation(Request $request)
    {
        $shopName = $request->header("url");

        $plan = $request->plan;

        if ($plan == 1) {
            $shop = Session::where("shop", $shopName)->first();

            $shop->plan = $plan;
            $shop->is_free = $plan;
            $shop->save();

            return Redirect()->back();

        }
        $variable = [

            "lineItems" => [
                [
                    "plan" => [
                        "appRecurringPricingDetails" => [
                            "price" => [
                                "currencyCode" => "USD",
                            ],
                        ],
                    ],
                ],
            ],
            "returnUrl" => route('active.charge') . "?shop=" . $shopName . '&plan=' . $plan,
            "test" => true,
            "trialDays" => 7,
        ];

        if ($plan == 2) {

            $variable['name'] = 'PLAN-1';
            $variable['lineItems'][0]['plan']['appRecurringPricingDetails']['price']['amount'] = 2.99;

        } else if ($plan == 3) {

            $variable['name'] = 'PLAN-2';
            $variable['lineItems'][0]['plan']['appRecurringPricingDetails']['price']['amount'] = 4.99;
        } else if ($plan == 1){
            $variable['name'] = 'FREE-PLAN';
            $variable['lineItems'][0]['plan']['appRecurringPricingDetails']['price']['amount'] = 0;
        }
        $query = 'mutation AppSubscriptionCreate($name: String!, $lineItems: [AppSubscriptionLineItemInput!]!, $returnUrl: URL!, $trialDays: Int, $test: Boolean) {
            appSubscriptionCreate(name: $name, returnUrl: $returnUrl, lineItems: $lineItems, trialDays: $trialDays, test: $test) {
              userErrors {
                field
                message
              }
              appSubscription {
                id
                name
              }
              confirmationUrl
            }
          }';

        $body = [
            "query" => $query,
            "variables" => $variable,
        ];

        $shop = Session::where('shop', $shopName)->first();
        info($shop);
        $response = $shop->graph($body);
        info($response);

        $confirmurl = $response['data']['appSubscriptionCreate']['confirmationUrl'];
        $planid = $response['data']['appSubscriptionCreate']['appSubscription']['id'];
        $planname = $response['data']['appSubscriptionCreate']['appSubscription']['name'];
        $arrOfPlan = [
            'id' => $planid,
            'name' => $planname,
            'confirmationUrl' => $confirmurl,
        ];

        return $arrOfPlan;
    }

    public function GetAppStatus(Request $request)
    {

        $shop = $request->header("url");
        $charge = Charge::where('shop', $shop)->first();
        $shopObj = Session::where('shop', $shop)->first();

        if ($shopObj->plan == 1) {
            return [
                "status" => 1,
                "data" => 1,
            ];
        }
        if ($charge) {

            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL, 'https://' . $shop . '/admin/api/2022-10/recurring_application_charges/' . $charge->charge_id . '.json');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

            $headers = array();
            $headers[] = 'X-Shopify-Access-Token: ' . $shopObj->access_token . '';
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close($ch);
            $chargeRes = json_decode($result, true);
            info($chargeRes);
            $chargeRes = $chargeRes['recurring_application_charge'];
            $plan = $chargeRes['price'] == '2.99' ? 1 : 2;
            $status = $chargeRes['status'] == "active" ? $plan : 0;
            // $charge->is_active = $status !== 0 ? 1 : 0;
            // $charge->save();
            return [
                "status" => 1,
                "data" => $status,
            ];
        }
        return [
            "status" => 1,
            "data" => 0,
        ];
    }
}
